### ISSUE TITLE
关于实验的问题

### ISSUE THREAD

**Issue by Julius666** [ykxhs/DILCR#3]
您好作者，请问一下论文里的
![屏幕截图 2024-06-24 100544](https://github.com/ykxhs/DILCR/assets/61342899/a245102e-0597-46e0-86a9-ae6ef89dcccd)
是使用什么工具绘图的

**Comment by ykxhs** [comment]
使用的matplotlib绘制

**Comment by Julius666** [comment]
好的好的，万分感谢！

**Comment by Julius666** [comment]
![屏幕截图 2024-07-02 115115](https://github.com/ykxhs/DILCR/assets/61342899/9d74c489-a785-4afd-b7a7-784de21b8ad8)
您好作者，这幅图也是使用matplotlib绘制的么？

**Comment by ykxhs** [comment]
> ![屏幕截图 2024-07-02 115115](https://private-user-images.githubusercontent.com/61342899/344869934-9d74c489-a785-4afd-b7a7-784de21b8ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDYyMjcsIm5iZiI6MTcyODQ0NTkyNywicGF0aCI6Ii82MTM0Mjg5OS8zNDQ4Njk5MzQtOWQ3NGM0ODktYTc4NS00YWZkLWI3YTctNzg0ZGUyMWI4YWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NmQ5YTg3ZmJkMGIyZTBkYjEwY2U0NWExN2YxZDE2NTZkYTk4NTE2M2JkNTZjZTdhNWZmZGRmNTVmMTU4ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uPOWWcCduEEk-NxNVn3jFLZNO5LnXpObIlNiK_gm_i4) 您好作者，这幅图也是使用matplotlib绘制的么？

R语言pheatmap绘制

**Comment by Julius666** [comment]
非常感谢！参考您的实验，我也投递了一篇论文已接近录用。
