### ISSUE TITLE
参数的问题

### ISSUE THREAD

**Issue by Julius666** [ykxhs/DILCR#4]
您好，作者，请问一下所有数据集的参数都是固定不变的么，不同的数据集是不是有特定的参数设置，如果您有时间的话可否在代码里put一下，万分感谢，这对我很重要。                                                                                          刘浩  18236220939（微信同号）

**Comment by ykxhs** [comment]
我们在实验中对部分数据集的参数有所调整，如果你要复现我们的实验，使用默认参数即可

**Comment by Julius666** [comment]
感谢作者的回复，除了预训练的轮数，我还应该修改那些参数呢，编码器的维度是不是也应该改变，因为某些数据集的结果我暂时还没有复现成功

**Comment by ykxhs** [comment]
参数只找到部分：if conf['dataset'] == "aml": #
                conf['cluster_num'] = 3
                conf['lr'] = 1e-5
                conf['pre_epochs'] = 2400
            if conf['dataset'] == "brca": #
                conf['cluster_num'] = 5
                conf['pre_epochs'] = 2000
            if conf['dataset'] == "skcm": #
                conf['cluster_num'] = 5
            if conf['dataset'] == "lihc": #
                conf['cluster_num'] = 5
                conf['pre_epochs'] = 1200
            if conf['dataset'] == "coad": #
                conf['cluster_num'] = 4
            if conf['dataset'] == "kirc": #
                conf['cluster_num'] = 4
            if conf['dataset'] == "gbm": #
                conf['cluster_num'] = 3
                conf['pre_epochs'] = 2000
                conf['batch_size'] = 64
                conf['cluster_var_dim'] = 64
                lmda_list['I_loss_lmda'] = 0.001
            if conf['dataset'] == "ov": # 1 / 2.7 3 500 64 64
                conf['cluster_num'] = 3
                conf['pre_epochs'] = 500
                conf['batch_size'] = 64
                conf['cluster_var_dim'] = 64
            if conf['dataset'] == "lusc": #.
                conf['cluster_num'] = 3
                conf['batch_size'] = 32
                conf['cluster_var_dim'] = 64
                conf['pre_epochs'] = 2000
            if conf['dataset'] == "sarc": #
                conf['cluster_num'] = 5
                conf['batch_size'] = 64
                conf['pre_epochs'] = 2500

**Comment by Julius666** [comment]
万分感谢，祝您好运天天，年年中顶刊！
